/**
 * MouseButtons.hh
 * Created by kate on 5/31/23.
 * */

#ifndef KATE_ENGINE_MOUSE_BUTTONS_HH
#define KATE_ENGINE_MOUSE_BUTTONS_HH

#include <GLFW/glfw3.h>

#if defined(USE_GLFW_MOUSE_CODES)
    #define KT_MOUSE_BUTTON_1       GLFW_MOUSE_BUTTON_1
    #define KT_MOUSE_BUTTON_2       GLFW_MOUSE_BUTTON_2
    #define KT_MOUSE_BUTTON_3       GLFW_MOUSE_BUTTON_3
    #define KT_MOUSE_BUTTON_4       GLFW_MOUSE_BUTTON_4
    #define KT_MOUSE_BUTTON_5       GLFW_MOUSE_BUTTON_5
    #define KT_MOUSE_BUTTON_6       GLFW_MOUSE_BUTTON_6
    #define KT_MOUSE_BUTTON_7       GLFW_MOUSE_BUTTON_7
    #define KT_MOUSE_BUTTON_8       GLFW_MOUSE_BUTTON_8
    #define KT_MOUSE_BUTTON_LAST    GLFW_MOUSE_BUTTON_LAST
    #define KT_MOUSE_BUTTON_LEFT    GLFW_MOUSE_BUTTON_LEFT
    #define KT_MOUSE_BUTTON_RIGHT   GLFW_MOUSE_BUTTON_RIGHT
    #define KT_MOUSE_BUTTON_MIDDLE  GLFW_MOUSE_BUTTON_MIDDLE
#endif

#endif//KATE_ENGINE_MOUSE_BUTTONS_HH
